// This file was automatically generated by make-pins.py
//
// --af boards/m487_af.csv
// --prefix boards/m48x_prefix.c

// m48x_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "mods/pybpin.h"

#define AF(p_port, p_pin, p_mfp, af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF_P##p_port##p_pin##_ ## af_fn ## af_unit ##_ ## af_type, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .reg = (af_ptr), \
    .mfp_val = SYS_GP##p_port##_##p_mfp##_P##p_port##p_pin##MFP_## af_fn ## af_unit##_##af_type, \
}

#define PIN(p_port, p_pin, p_mfp, p_af, p_adc_num, p_adc_channel) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
    .pin_mask = (1 << ((p_pin) & 0x0f)), \
    .gpio = P ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
    .mfp_reg = &SYS->GP##p_port##_##p_mfp, \
    .mfos_reg = &SYS->GP##p_port##_MFOS, \
}

// --board boards/NuMaker-PFM-M487/pins.csv
const pin_af_obj_t pin_A0_af[] = {
  AF(A, 0, MFPL,  0, SPIM    ,  0, MOSI      , SPIM0   ), // SPIM0_MOSI
  AF(A, 0, MFPL,  1, QSPI    ,  0, MOSI0     , QSPI0   ), // QSPI0_MOSI0
  AF(A, 0, MFPL,  2, SPI     ,  0, MOSI      , SPI0    ), // SPI0_MOSI
  AF(A, 0, MFPL,  3, SD      ,  1, DAT0      , SD1     ), // SD1_DAT0
  AF(A, 0, MFPL,  4, SC      ,  0, CLK       , SC0     ), // SC0_CLK
  AF(A, 0, MFPL,  5, UART    ,  0, RXD       , UART0   ), // UART0_RXD
  AF(A, 0, MFPL,  6, UART    ,  1, nRTS      , UART1   ), // UART1_nRTS
  AF(A, 0, MFPL,  7, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
  AF(A, 0, MFPL,  8, BPWM    ,  0, CH0       , BPWM0   ), // BPWM0_CH0
  AF(A, 0, MFPL,  9, EPWM    ,  0, CH5       , EPWM0   ), // EPWM0_CH5
  AF(A, 0, MFPL, 10, DAC     ,  0, ST        , DAC0    ), // DAC0_ST
  //(A, 0, MFPL, 11, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A0_obj = PIN(A, 0, MFPL, pin_A0_af, 0, 0);

const pin_af_obj_t pin_A1_af[] = {
  AF(A, 1, MFPL,  0, SPIM    ,  0, MISO      , SPIM0   ), // SPIM0_MISO
  AF(A, 1, MFPL,  1, QSPI    ,  0, MISO0     , QSPI0   ), // QSPI0_MISO0
  AF(A, 1, MFPL,  2, SPI     ,  0, MISO      , SPI0    ), // SPI0_MISO
  AF(A, 1, MFPL,  3, SD      ,  1, DAT1      , SD1     ), // SD1_DAT1
  AF(A, 1, MFPL,  4, SC      ,  0, DAT       , SC0     ), // SC0_DAT
  AF(A, 1, MFPL,  5, UART    ,  0, TXD       , UART0   ), // UART0_TXD
  AF(A, 1, MFPL,  6, UART    ,  1, nCTS      , UART1   ), // UART1_nCTS
  AF(A, 1, MFPL,  7, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
  AF(A, 1, MFPL,  8, BPWM    ,  0, CH1       , BPWM0   ), // BPWM0_CH1
  AF(A, 1, MFPL,  9, EPWM    ,  0, CH4       , EPWM0   ), // EPWM0_CH4
  AF(A, 1, MFPL, 10, DAC     ,  1, ST        , DAC1    ), // DAC1_ST
  //(A, 1, MFPL, 11, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A1_obj = PIN(A, 1, MFPL, pin_A1_af, 0, 0);

const pin_af_obj_t pin_A2_af[] = {
  AF(A, 2, MFPL,  0, SPIM    ,  0, CLK       , SPIM0   ), // SPIM0_CLK
  AF(A, 2, MFPL,  1, QSPI    ,  0, CLK       , QSPI0   ), // QSPI0_CLK
  AF(A, 2, MFPL,  2, SPI     ,  0, CLK       , SPI0    ), // SPI0_CLK
  AF(A, 2, MFPL,  3, SD      ,  1, DAT2      , SD1     ), // SD1_DAT2
  AF(A, 2, MFPL,  4, SC      ,  0, RST       , SC0     ), // SC0_RST
  AF(A, 2, MFPL,  5, UART    ,  4, RXD       , UART4   ), // UART4_RXD
  AF(A, 2, MFPL,  6, UART    ,  1, RXD       , UART1   ), // UART1_RXD
  AF(A, 2, MFPL,  7, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  AF(A, 2, MFPL,  8, BPWM    ,  0, CH2       , BPWM0   ), // BPWM0_CH2
  AF(A, 2, MFPL,  9, EPWM    ,  0, CH3       , EPWM0   ), // EPWM0_CH3
  //(A, 2, MFPL, 10, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A2_obj = PIN(A, 2, MFPL, pin_A2_af, 0, 0);

const pin_af_obj_t pin_A3_af[] = {
  AF(A, 3, MFPL,  0, SPIM    ,  0, SS        , SPIM0   ), // SPIM0_SS
  AF(A, 3, MFPL,  1, QSPI    ,  0, SS        , QSPI0   ), // QSPI0_SS
  AF(A, 3, MFPL,  2, SPI     ,  0, SS        , SPI0    ), // SPI0_SS
  AF(A, 3, MFPL,  3, SD      ,  1, DAT3      , SD1     ), // SD1_DAT3
  AF(A, 3, MFPL,  4, SC      ,  0, PWR       , SC0     ), // SC0_PWR
  AF(A, 3, MFPL,  5, UART    ,  4, TXD       , UART4   ), // UART4_TXD
  AF(A, 3, MFPL,  6, UART    ,  1, TXD       , UART1   ), // UART1_TXD
  AF(A, 3, MFPL,  7, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  AF(A, 3, MFPL,  8, BPWM    ,  0, CH3       , BPWM0   ), // BPWM0_CH3
  AF(A, 3, MFPL,  9, EPWM    ,  0, CH2       , EPWM0   ), // EPWM0_CH2
  AF(A, 3, MFPL, 10, QEI     ,  0, B         , QEI0    ), // QEI0_B
  //(A, 3, MFPL, 11, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A3_obj = PIN(A, 3, MFPL, pin_A3_af, 0, 0);

const pin_af_obj_t pin_A4_af[] = {
  AF(A, 4, MFPL,  0, SPIM    ,  0, D3        , SPIM0   ), // SPIM0_D3
  AF(A, 4, MFPL,  1, QSPI    ,  0, MOSI1     , QSPI0   ), // QSPI0_MOSI1
  AF(A, 4, MFPL,  2, SPI     ,  0, I2SMCLK   , SPI0    ), // SPI0_I2SMCLK
  AF(A, 4, MFPL,  3, SD      ,  1, CLK       , SD1     ), // SD1_CLK
  AF(A, 4, MFPL,  4, SC      ,  0, nCD       , SC0     ), // SC0_nCD
  AF(A, 4, MFPL,  5, UART    ,  0, nRTS      , UART0   ), // UART0_nRTS
  AF(A, 4, MFPL,  6, UART    ,  5, RXD       , UART5   ), // UART5_RXD
  AF(A, 4, MFPL,  7, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  AF(A, 4, MFPL,  8, CAN     ,  0, RXD       , CAN0    ), // CAN0_RXD
  AF(A, 4, MFPL,  9, BPWM    ,  0, CH4       , BPWM0   ), // BPWM0_CH4
  AF(A, 4, MFPL, 10, EPWM    ,  0, CH1       , EPWM0   ), // EPWM0_CH1
  AF(A, 4, MFPL, 11, QEI     ,  0, A         , QEI0    ), // QEI0_A
  //(A, 4, MFPL, 12, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A4_obj = PIN(A, 4, MFPL, pin_A4_af, 0, 0);

const pin_af_obj_t pin_A5_af[] = {
  AF(A, 5, MFPL,  0, SPIM    ,  0, D2        , SPIM0   ), // SPIM0_D2
  AF(A, 5, MFPL,  1, QSPI    ,  0, MISO1     , QSPI0   ), // QSPI0_MISO1
  AF(A, 5, MFPL,  2, SPI     ,  1, I2SMCLK   , SPI1    ), // SPI1_I2SMCLK
  AF(A, 5, MFPL,  3, SD      ,  1, CMD       , SD1     ), // SD1_CMD
  AF(A, 5, MFPL,  4, SC      ,  2, nCD       , SC2     ), // SC2_nCD
  AF(A, 5, MFPL,  5, UART    ,  0, nCTS      , UART0   ), // UART0_nCTS
  AF(A, 5, MFPL,  6, UART    ,  5, TXD       , UART5   ), // UART5_TXD
  AF(A, 5, MFPL,  7, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  AF(A, 5, MFPL,  8, CAN     ,  0, TXD       , CAN0    ), // CAN0_TXD
  AF(A, 5, MFPL,  9, BPWM    ,  0, CH5       , BPWM0   ), // BPWM0_CH5
  AF(A, 5, MFPL, 10, EPWM    ,  0, CH0       , EPWM0   ), // EPWM0_CH0
  AF(A, 5, MFPL, 11, QEI     ,  0, INDEX     , QEI0    ), // QEI0_INDEX
  //(A, 5, MFPL, 12, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A5_obj = PIN(A, 5, MFPL, pin_A5_af, 0, 0);

const pin_af_obj_t pin_B0_af[] = {
  AF(B, 0, MFPL,  0, SPI     ,  0, I2SMCLK   , SPI0    ), // SPI0_I2SMCLK
  AF(B, 0, MFPL,  1, SD      ,  0, CMD       , SD0     ), // SD0_CMD
  AF(B, 0, MFPL,  2, UART    ,  2, RXD       , UART2   ), // UART2_RXD
  AF(B, 0, MFPL,  3, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  AF(B, 0, MFPL,  4, EPWM    ,  0, CH5       , EPWM0   ), // EPWM0_CH5
  AF(B, 0, MFPL,  5, EPWM    ,  1, CH5       , EPWM1   ), // EPWM1_CH5
  AF(B, 0, MFPL,  6, EPWM    ,  0, BRAKE1    , EPWM0   ), // EPWM0_BRAKE1
  AF(B, 0, MFPL,  7, OPA     ,  0, P         , OPA0    ), // OPA0_P
  AF(B, 0, MFPL,  8, EBI     ,  0, ADR9      , EBI0    ), // EBI0_ADR9
  AF(B, 0, MFPL,  9, EADC    ,  0, CH0       , EADC0   ), // EADC0_CH0
  //(B, 0, MFPL, 10, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B0_obj = PIN(B, 0, MFPL, pin_B0_af, 0, 0);

const pin_af_obj_t pin_B1_af[] = {
  AF(B, 1, MFPL,  0, EADC    ,  0, CH1       , EADC0   ), // EADC0_CH1
  AF(B, 1, MFPL,  1, OPA     ,  0, N         , OPA0    ), // OPA0_N
  AF(B, 1, MFPL,  2, EBI     ,  0, ADR8      , EBI0    ), // EBI0_ADR8
  AF(B, 1, MFPL,  3, SD      ,  0, CLK       , SD0     ), // SD0_CLK
  AF(B, 1, MFPL,  4, EMAC    ,  0, RMII_RXERR, EMAC0   ), // EMAC0_RMII_RXERR
  AF(B, 1, MFPL,  5, SPI     ,  1, I2SMCLK   , SPI1    ), // SPI1_I2SMCLK
  AF(B, 1, MFPL,  6, SPI     ,  3, I2SMCLK   , SPI3    ), // SPI3_I2SMCLK
  AF(B, 1, MFPL,  7, UART    ,  2, TXD       , UART2   ), // UART2_TXD
  AF(B, 1, MFPL,  8, USCI    ,  1, CLK       , USCI1   ), // USCI1_CLK
  AF(B, 1, MFPL,  9, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  AF(B, 1, MFPL, 10, I2S     ,  0, LRCK      , I2S0    ), // I2S0_LRCK
  AF(B, 1, MFPL, 11, EPWM    ,  0, CH4       , EPWM0   ), // EPWM0_CH4
  AF(B, 1, MFPL, 12, EPWM    ,  1, CH4       , EPWM1   ), // EPWM1_CH4
  AF(B, 1, MFPL, 13, EPWM    ,  0, BRAKE0    , EPWM0   ), // EPWM0_BRAKE0
  //(B, 1, MFPL, 14, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B1_obj = PIN(B, 1, MFPL, pin_B1_af, 0, 0);

const pin_af_obj_t pin_B2_af[] = {
  AF(B, 2, MFPL,  0, ACMP    ,  0, P1        , ACMP0   ), // ACMP0_P1
  AF(B, 2, MFPL,  1, EADC    ,  0, CH2       , EADC0   ), // EADC0_CH2
  AF(B, 2, MFPL,  2, OPA     ,  0, O         , OPA0    ), // OPA0_O
  AF(B, 2, MFPL,  3, EBI     ,  0, ADR3      , EBI0    ), // EBI0_ADR3
  AF(B, 2, MFPL,  4, SD      ,  0, DAT0      , SD0     ), // SD0_DAT0
  AF(B, 2, MFPL,  5, EMAC    ,  0, RMII_CRSDV, EMAC0   ), // EMAC0_RMII_CRSDV
  AF(B, 2, MFPL,  6, SPI     ,  1, SS        , SPI1    ), // SPI1_SS
  AF(B, 2, MFPL,  7, UART    ,  1, RXD       , UART1   ), // UART1_RXD
  AF(B, 2, MFPL,  8, UART    ,  5, nCTS      , UART5   ), // UART5_nCTS
  AF(B, 2, MFPL,  9, USCI    ,  1, DAT0      , USCI1   ), // USCI1_DAT0
  AF(B, 2, MFPL, 10, SC      ,  0, PWR       , SC0     ), // SC0_PWR
  AF(B, 2, MFPL, 11, I2S     ,  0, DO        , I2S0    ), // I2S0_DO
  AF(B, 2, MFPL, 12, EPWM    ,  0, CH3       , EPWM0   ), // EPWM0_CH3
  AF(B, 2, MFPL, 13, TMR     ,  3, TMR       , TMR3    ), // TMR3_TMR
  AF(B, 2, MFPL, 14, INT     ,  3, INT       , INT3    ), // INT3_INT
  //(B, 2, MFPL, 15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B2_obj = PIN(B, 2, MFPL, pin_B2_af, 0, 0);

const pin_af_obj_t pin_B3_af[] = {
  AF(B, 3, MFPL,  0, ACMP    ,  0, N         , ACMP0   ), // ACMP0_N
  AF(B, 3, MFPL,  1, EADC    ,  0, CH3       , EADC0   ), // EADC0_CH3
  AF(B, 3, MFPL,  2, EBI     ,  0, ADR2      , EBI0    ), // EBI0_ADR2
  AF(B, 3, MFPL,  3, SD      ,  0, DAT1      , SD0     ), // SD0_DAT1
  AF(B, 3, MFPL,  4, EMAC    ,  0, RMII_RXD1 , EMAC0   ), // EMAC0_RMII_RXD1
  AF(B, 3, MFPL,  5, SPI     ,  1, CLK       , SPI1    ), // SPI1_CLK
  AF(B, 3, MFPL,  6, UART    ,  1, TXD       , UART1   ), // UART1_TXD
  AF(B, 3, MFPL,  7, UART    ,  5, nRTS      , UART5   ), // UART5_nRTS
  AF(B, 3, MFPL,  8, USCI    ,  1, DAT1      , USCI1   ), // USCI1_DAT1
  AF(B, 3, MFPL,  9, SC      ,  0, RST       , SC0     ), // SC0_RST
  AF(B, 3, MFPL, 10, I2S     ,  0, DI        , I2S0    ), // I2S0_DI
  AF(B, 3, MFPL, 11, EPWM    ,  0, CH2       , EPWM0   ), // EPWM0_CH2
  AF(B, 3, MFPL, 12, TMR     ,  2, TMR       , TMR2    ), // TMR2_TMR
  AF(B, 3, MFPL, 13, INT     ,  2, INT       , INT2    ), // INT2_INT
  //(B, 3, MFPL, 14, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B3_obj = PIN(B, 3, MFPL, pin_B3_af, 0, 0);

const pin_af_obj_t pin_B6_af[] = {
  AF(B, 6, MFPL,  0, EADC    ,  0, CH6       , EADC0   ), // EADC0_CH6
  AF(B, 6, MFPL,  1, EBI     ,  0, nWRH      , EBI0    ), // EBI0_nWRH
  AF(B, 6, MFPL,  2, EBI     ,  0, nCS1      , EBI0    ), // EBI0_nCS1
  AF(B, 6, MFPL,  3, EMAC    ,  0, PPS       , EMAC0   ), // EMAC0_PPS
  AF(B, 6, MFPL,  4, USCI    ,  1, DAT1      , USCI1   ), // USCI1_DAT1
  AF(B, 6, MFPL,  5, CAN     ,  1, RXD       , CAN1    ), // CAN1_RXD
  AF(B, 6, MFPL,  6, UART    ,  1, RXD       , UART1   ), // UART1_RXD
  AF(B, 6, MFPL,  7, SD      ,  1, CLK       , SD1     ), // SD1_CLK
  AF(B, 6, MFPL,  8, BPWM    ,  1, CH5       , BPWM1   ), // BPWM1_CH5
  AF(B, 6, MFPL,  9, EPWM    ,  1, BRAKE1    , EPWM1   ), // EPWM1_BRAKE1
  AF(B, 6, MFPL, 10, EPWM    ,  1, CH5       , EPWM1   ), // EPWM1_CH5
  AF(B, 6, MFPL, 11, INT     ,  4, INT       , INT4    ), // INT4_INT
  //(B, 6, MFPL, 12, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B6_obj = PIN(B, 6, MFPL, pin_B6_af, 0, 0);

const pin_af_obj_t pin_B7_af[] = {
  AF(B, 7, MFPL,  0, EADC    ,  0, CH7       , EADC0   ), // EADC0_CH7
  AF(B, 7, MFPL,  1, EBI     ,  0, nWRL      , EBI0    ), // EBI0_nWRL
  AF(B, 7, MFPL,  2, EBI     ,  0, nCS0      , EBI0    ), // EBI0_nCS0
  AF(B, 7, MFPL,  3, EMAC    ,  0, RMII_TXEN , EMAC0   ), // EMAC0_RMII_TXEN
  AF(B, 7, MFPL,  4, USCI    ,  1, DAT0      , USCI1   ), // USCI1_DAT0
  AF(B, 7, MFPL,  5, CAN     ,  1, TXD       , CAN1    ), // CAN1_TXD
  AF(B, 7, MFPL,  6, UART    ,  1, TXD       , UART1   ), // UART1_TXD
  AF(B, 7, MFPL,  7, SD      ,  1, CMD       , SD1     ), // SD1_CMD
  AF(B, 7, MFPL,  8, BPWM    ,  1, CH4       , BPWM1   ), // BPWM1_CH4
  AF(B, 7, MFPL,  9, EPWM    ,  1, BRAKE0    , EPWM1   ), // EPWM1_BRAKE0
  AF(B, 7, MFPL, 10, EPWM    ,  1, CH4       , EPWM1   ), // EPWM1_CH4
  AF(B, 7, MFPL, 11, INT     ,  5, INT       , INT5    ), // INT5_INT
  //(B, 7, MFPL, 12, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B7_obj = PIN(B, 7, MFPL, pin_B7_af, 0, 0);

const pin_af_obj_t pin_B8_af[] = {
  AF(B, 8, MFPH,  0, EADC    ,  0, CH8       , EADC0   ), // EADC0_CH8
  AF(B, 8, MFPH,  1, EBI     ,  0, ADR19     , EBI     ), // EBI_ADR19
  AF(B, 8, MFPH,  2, EMAC    ,  0, RMII_TXD1 , EMAC0   ), // EMAC0_RMII_TXD1
  AF(B, 8, MFPH,  3, USCI    ,  1, CLK       , USCI1   ), // USCI1_CLK
  AF(B, 8, MFPH,  4, UART    ,  0, RXD       , UART0   ), // UART0_RXD
  AF(B, 8, MFPH,  5, UART    ,  1, nRTS      , UART1   ), // UART1_nRTS
  AF(B, 8, MFPH,  6, I2C     ,  1, SMBSUS    , I2C1    ), // I2C1_SMBSUS
  AF(B, 8, MFPH,  7, BPWM    ,  1, CH3       , BPWM1   ), // BPWM1_CH3
  AF(B, 8, MFPH,  8, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
  AF(B, 8, MFPH,  9, INT     ,  6, INT       , INT6    ), // INT6_INT
  //(B, 8, MFPH, 10, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B8_obj = PIN(B, 8, MFPH, pin_B8_af, 0, 0);

const pin_af_obj_t pin_B9_af[] = {
  AF(B, 9, MFPH,  0, EADC    ,  0, CH9       , EADC0   ), // EADC0_CH9
  AF(B, 9, MFPH,  1, EBI     ,  0, ADR18     , EBI0    ), // EBI0_ADR18
  AF(B, 9, MFPH,  2, EMAC    ,  0, RMII_TXD0 , EMAC    ), // EMAC_RMII_TXD0
  AF(B, 9, MFPH,  3, USCI    ,  1, CTL1      , USCI1   ), // USCI1_CTL1
  AF(B, 9, MFPH,  4, UART    ,  0, TXD       , UART0   ), // UART0_TXD
  AF(B, 9, MFPH,  5, UART    ,  1, nCTS      , UART1   ), // UART1_nCTS
  AF(B, 9, MFPH,  6, I2C     ,  1, SMBAL     , I2C1    ), // I2C1_SMBAL
  AF(B, 9, MFPH,  7, BPWM    ,  1, CH2       , BPWM1   ), // BPWM1_CH2
  AF(B, 9, MFPH,  8, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
  AF(B, 9, MFPH,  9, INT     ,  7, INT       , INT7    ), // INT7_INT
  //(B, 9, MFPH, 10, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B9_obj = PIN(B, 9, MFPH, pin_B9_af, 0, 0);

const pin_af_obj_t pin_B12_af[] = {
  AF(B, 12, MFPH,  0, ACMP    ,  0, P2        , ACMP0   ), // ACMP0_P2
  AF(B, 12, MFPH,  1, ACMP    ,  1, P2        , ACMP1   ), // ACMP1_P2
  AF(B, 12, MFPH,  2, DAC     ,  0, OUT       , DAC0    ), // DAC0_OUT
  AF(B, 12, MFPH,  3, EADC    ,  0, CH12      , EADC0   ), // EADC0_CH12
  AF(B, 12, MFPH,  4, EBI     ,  0, AD15      , EBI0    ), // EBI0_AD15
  AF(B, 12, MFPH,  5, SC      ,  1, CLK       , SC1     ), // SC1_CLK
  AF(B, 12, MFPH,  6, SPI     ,  0, MOSI      , SPI0    ), // SPI0_MOSI
  AF(B, 12, MFPH,  7, USCI    ,  0, CLK       , USCI0   ), // USCI0_CLK
  AF(B, 12, MFPH,  8, UART    ,  0, RXD       , UART0   ), // UART0_RXD
  AF(B, 12, MFPH,  9, UART    ,  3, nCTS      , UART3   ), // UART3_nCTS
  AF(B, 12, MFPH, 10, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
  AF(B, 12, MFPH, 11, SD      ,  0, nCD       , SD0     ), // SD0_nCD
  AF(B, 12, MFPH, 12, EPWM    ,  1, CH3       , EPWM1   ), // EPWM1_CH3
  AF(B, 12, MFPH, 13, TMR     ,  3, EXT       , TMR3    ), // TMR3_EXT
  //(B, 12, MFPH, 14, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B12_obj = PIN(B, 12, MFPH, pin_B12_af, 0, 0);

const pin_af_obj_t pin_C9_af[] = {
  AF(C, 9, MFPH,  0, EBI     ,  0, ADR7      , EBI0    ), // EBI0_ADR7
  AF(C, 9, MFPH,  1, SPI     ,  3, SS        , SPI3    ), // SPI3_SS
  AF(C, 9, MFPH,  2, UART    ,  3, RXD       , UART3   ), // UART3_RXD
  AF(C, 9, MFPH,  3, CAN     ,  1, RXD       , CAN1    ), // CAN1_RXD
  AF(C, 9, MFPH,  4, EPWM    ,  1, CH3       , EPWM1   ), // EPWM1_CH3
  //(C, 9, MFPH,  5, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C9_obj = PIN(C, 9, MFPH, pin_C9_af, 0, 0);

const pin_af_obj_t pin_C10_af[] = {
  AF(C, 10, MFPH,  0, EBI     ,  0, ADR6      , EBI0    ), // EBI0_ADR6
  AF(C, 10, MFPH,  1, SPI     ,  3, CLK       , SPI3    ), // SPI3_CLK
  AF(C, 10, MFPH,  2, UART    ,  3, TXD       , UART3   ), // UART3_TXD
  AF(C, 10, MFPH,  3, CAN     ,  1, TXD       , CAN1    ), // CAN1_TXD
  AF(C, 10, MFPH,  4, ECAP    ,  1, IC0       , ECAP1   ), // ECAP1_IC0
  AF(C, 10, MFPH,  5, EPWM    ,  1, CH2       , EPWM1   ), // EPWM1_CH2
  //(C, 10, MFPH,  6, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C10_obj = PIN(C, 10, MFPH, pin_C10_af, 0, 0);

const pin_af_obj_t pin_C11_af[] = {
  AF(C, 11, MFPH,  0, EBI     ,  0, ADR5      , EBI0    ), // EBI0_ADR5
  AF(C, 11, MFPH,  1, UART    ,  0, RXD       , UART0   ), // UART0_RXD
  AF(C, 11, MFPH,  2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  AF(C, 11, MFPH,  3, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
  AF(C, 11, MFPH,  4, ECAP    ,  1, IC1       , ECAP1   ), // ECAP1_IC1
  AF(C, 11, MFPH,  5, EPWM    ,  1, CH1       , EPWM1   ), // EPWM1_CH1
  AF(C, 11, MFPH,  6, ACMP    ,  1, O         , ACMP1   ), // ACMP1_O
  //(C, 11, MFPH,  7, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C11_obj = PIN(C, 11, MFPH, pin_C11_af, 0, 0);

const pin_af_obj_t pin_C12_af[] = {
  AF(C, 12, MFPH,  0, EBI     ,  0, ADR4      , EBI0    ), // EBI0_ADR4
  AF(C, 12, MFPH,  1, UART    ,  0, TXD       , UART0   ), // UART0_TXD
  AF(C, 12, MFPH,  2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  AF(C, 12, MFPH,  3, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
  AF(C, 12, MFPH,  4, SC      ,  0, nCD       , SC0     ), // SC0_nCD
  AF(C, 12, MFPH,  5, ECAP    ,  1, IC2       , ECAP1   ), // ECAP1_IC2
  AF(C, 12, MFPH,  6, EPWM    ,  1, CH0       , EPWM1   ), // EPWM1_CH0
  AF(C, 12, MFPH,  7, ACMP    ,  0, O         , ACMP0   ), // ACMP0_O
  //(C, 12, MFPH,  8, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C12_obj = PIN(C, 12, MFPH, pin_C12_af, 0, 0);

const pin_af_obj_t pin_E4_af[] = {
  AF(E, 4, MFPL,  0, EBI     ,  0, nWR       , EBI0    ), // EBI0_nWR
  AF(E, 4, MFPL,  1, SD      ,  0, DAT2      , SD0     ), // SD0_DAT2
  AF(E, 4, MFPL,  2, SPIM    ,  0, CLK       , SPIM0   ), // SPIM0_CLK
  AF(E, 4, MFPL,  3, SPI     ,  3, CLK       , SPI3    ), // SPI3_CLK
  AF(E, 4, MFPL,  4, SC      ,  0, RST       , SC0     ), // SC0_RST
  AF(E, 4, MFPL,  5, USCI    ,  0, DAT1      , USCI0   ), // USCI0_DAT1
  AF(E, 4, MFPL,  6, QEI     ,  0, INDEX     , QEI0    ), // QEI0_INDEX
  AF(E, 4, MFPL,  7, EPWM    ,  0, CH3       , EPWM0   ), // EPWM0_CH3
  AF(E, 4, MFPL,  8, BPWM    ,  0, CH2       , BPWM0   ), // BPWM0_CH2
  //(E, 4, MFPL,  9, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E4_obj = PIN(E, 4, MFPL, pin_E4_af, 0, 0);

const pin_af_obj_t pin_E5_af[] = {
  AF(E, 5, MFPL,  0, EBI     ,  0, nRD       , EBI0    ), // EBI0_nRD
  AF(E, 5, MFPL,  1, SD      ,  0, DAT3      , SD0     ), // SD0_DAT3
  AF(E, 5, MFPL,  2, SPIM    ,  0, SS        , SPIM0   ), // SPIM0_SS
  AF(E, 5, MFPL,  3, SPI     ,  3, SS        , SPI3    ), // SPI3_SS
  AF(E, 5, MFPL,  4, SC      ,  0, PWR       , SC0     ), // SC0_PWR
  AF(E, 5, MFPL,  5, USCI    ,  0, CTL1      , USCI0   ), // USCI0_CTL1
  AF(E, 5, MFPL,  6, QEI     ,  1, B         , QEI1    ), // QEI1_B
  AF(E, 5, MFPL,  7, EPWM    ,  0, CH2       , EPWM0   ), // EPWM0_CH2
  AF(E, 5, MFPL,  8, BPWM    ,  0, CH3       , BPWM0   ), // BPWM0_CH3
  //(E, 5, MFPL,  9, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E5_obj = PIN(E, 5, MFPL, pin_E5_af, 0, 0);

const pin_af_obj_t pin_F11_af[] = {
  AF(F, 11, MFPH,  0, EBI     ,  0, ADR14     , EBI0    ), // EBI0_ADR14
  AF(F, 11, MFPH,  1, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
  AF(F, 11, MFPH,  2, TAMPER  ,  5, TAMPER    , TAMPER5 ), // TAMPER5_TAMPER
  AF(F, 11, MFPH,  3, TMR     ,  3, TMR       , TMR3    ), // TMR3_TMR
  //(F, 11, MFPH,  4, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F11_obj = PIN(F, 11, MFPH, pin_F11_af, 0, 0);

const pin_af_obj_t pin_G15_af[] = {
  AF(G, 15, MFPH,  0, SD      ,  1, nCD       , SD1     ), // SD1_nCD
  AF(G, 15, MFPH,  1, EADC    ,  0, ST        , EADC0   ), // EADC0_ST
  //(G, 15, MFPH,  2, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G15_obj = PIN(G, 15, MFPH, pin_G15_af, 0, 0);

const pin_af_obj_t pin_H0_af[] = {
  AF(H, 0, MFPL,  0, EBI     ,  0, ADR7      , EBI0    ), // EBI0_ADR7
  AF(H, 0, MFPL,  1, UART    ,  5, TXD       , UART5   ), // UART5_TXD
  AF(H, 0, MFPL,  2, TMR     ,  0, EXT       , TMR0    ), // TMR0_EXT
  //(H, 0, MFPL,  3, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H0_obj = PIN(H, 0, MFPL, pin_H0_af, 0, 0);

const pin_af_obj_t pin_H1_af[] = {
  AF(H, 1, MFPL,  0, EBI     ,  0, ADR6      , EBI0    ), // EBI0_ADR6
  AF(H, 1, MFPL,  1, UART    ,  5, RXD       , UART5   ), // UART5_RXD
  AF(H, 1, MFPL,  2, TMR     ,  1, EXT       , TMR1    ), // TMR1_EXT
  //(H, 1, MFPL,  3, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H1_obj = PIN(H, 1, MFPL, pin_H1_af, 0, 0);

const pin_af_obj_t pin_H2_af[] = {
  AF(H, 2, MFPL,  0, EBI     ,  0, ADR5      , EBI0    ), // EBI0_ADR5
  AF(H, 2, MFPL,  1, UART    ,  5, nRTS      , UART5   ), // UART5_nRTS
  AF(H, 2, MFPL,  2, UART    ,  4, TXD       , UART4   ), // UART4_TXD
  AF(H, 2, MFPL,  3, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  AF(H, 2, MFPL,  4, TMR     ,  2, EXT       , TMR2    ), // TMR2_EXT
  //(H, 2, MFPL,  5, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H2_obj = PIN(H, 2, MFPL, pin_H2_af, 0, 0);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_A4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_A5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_B0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_B1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_B2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_B3), MP_ROM_PTR(&pin_B3_obj) },
  { MP_ROM_QSTR(MP_QSTR_B6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_B7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_B8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_B9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_B12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_C9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_C10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_C11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_C12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_E4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_E5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_F11), MP_ROM_PTR(&pin_F11_obj) },
  { MP_ROM_QSTR(MP_QSTR_G15), MP_ROM_PTR(&pin_G15_obj) },
  { MP_ROM_QSTR(MP_QSTR_H0), MP_ROM_PTR(&pin_H0_obj) },
  { MP_ROM_QSTR(MP_QSTR_H1), MP_ROM_PTR(&pin_H1_obj) },
  { MP_ROM_QSTR(MP_QSTR_H2), MP_ROM_PTR(&pin_H2_obj) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_D0), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_D1), MP_ROM_PTR(&pin_B3_obj) },
  { MP_ROM_QSTR(MP_QSTR_D2), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_D3), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_D4), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_D5), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_D7), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_D11), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_D12), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_A4), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_A5), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_SW2), MP_ROM_PTR(&pin_G15_obj) },
  { MP_ROM_QSTR(MP_QSTR_SW3), MP_ROM_PTR(&pin_F11_obj) },
  { MP_ROM_QSTR(MP_QSTR_LEDR), MP_ROM_PTR(&pin_H0_obj) },
  { MP_ROM_QSTR(MP_QSTR_LEDY), MP_ROM_PTR(&pin_H1_obj) },
  { MP_ROM_QSTR(MP_QSTR_LEDG), MP_ROM_PTR(&pin_H2_obj) },
  { MP_ROM_QSTR(MP_QSTR_DAC0_OUT), MP_ROM_PTR(&pin_B12_obj) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);
