
#define MICROPY_HW_BOARD_NAME "NHS-N3292x-1-CF"

#define MICROPY_HW_BOARD_NHS_N3292x_1_CF

//RTC
#define MICROPY_HW_ENABLE_RTC       (1)

//VPOST
#define MICROPY_HW_ENABLE_VPOST     (1)

//Touch ADC
#define MICROPY_HW_ENABLE_TOUCHADC	(1)
